authorname: "Yingxiao Yan"
draft: false

project:
  type: website
  output-dir: doc
  resources:
    - "img/**"
    - "icon/**"
    - "pdf/**"
    - "_extensions/**"
  preview:
    port: 22223
    browser: true
    watch-inputs: true
    navigate: true

#title-meta: "TriplotGUI"
#description-meta: "Epidemiologist | PhD researcher | Machine learning, computational metabolomics"


name: "TriplotGUI"
website:
  bread-crumbs: true
  page-navigation: true
  repo-actions: [edit, source, issue]
  title: "TriplotGUI {{< fa brands gitlab >}}"
  description: "Epidemiologist | PhD researcher | Machine learning, computational metabolomics"
  image: img/TriplotGUI_logo_white.png
  favicon: img/TriplotGUI_logo_white.png
  site-url: "https://yingxiaoyan.gitlab.io/triplotgui_tutorial/"
  repo-url: "https://gitlab.com/YingxiaoYan/triplotgui_tutorial"
  repo-branch: main
  search:
    location: navbar
    type: textbox
    copy-button: true
    collapse-after: 5
    # algolia:
    #   index-name: TriplotGUI
    #   application-id: YC8NCKROXT
    #   search-only-api-key: 0b4c49741cbded7ded632b969ef356cc
    #   analytics-events: true
    #   show-logo: true
    #   index-fields:
    #     href: https://yingxiaoyan.gitlab.io/triplotgui_tutorial/
    #     title: doc_title
    #     text: doc_content
    #     section: doc_section
  navbar:
    logo: /img/TriplotGUI_logo_black.png
    pinned: true
    foreground: yellow
    background: black   # It seems title block banner background color change with it
    left:
      - href: introduction.qmd
        text: Introduction
      - href: installation.qmd
        text: Setup
      - href: workflow.qmd
        text: Manual
      - text: Tutorial(simple)
        menu:
          - href: simple.qmd
            text: User Interface
          - href: simple_code.qmd
            text: Code
      - text: Tutorial(complex)
        menu:
          - href: complex.qmd
            text: User Interface
          - href: complex_code.qmd
            text: Code
      #- text: Use Case
      #  href: use_case.qmd
      - text: Papers
        href: papers.qmd
      - href: about.qmd
        text: About us

    right:
      - icon: folder-symlink
        href: https://yingxiaoyan.gitlab.io/triplotgui_tutorial/
        target: _blank
      #- icon: git
      #  href: https://gitlab.com/YingxiaoYan/TriplotGUI
      - icon: linkedin
        href: https://www.linkedin.com/in/yingxiao-yan
        target: _blank
      - icon: envelope
        aria-label: email
        href: "mailto:yingxiao@chalmers.se"
  page-footer:
    background: light
    left: |
      <span class="faux-block">&#169; 2024 Yingxiao Yan <br> CC BY-SA 4.0</span>
    center: |
      <span class="faux-block">
      <a href="https://yingxiao.shinyapps.io/triplotgui/" target="_blank">TriplotGUI</a> <br>
      <a href="https://gitlab.com/YingxiaoYan/TriplotGUI" target="_blank">TriplotGUI Gitlab</a>
      </span>
    right: |
      <span class="faux-block cyan">
      <a href="https://yingxiaoyan.gitlab.io/triplotgui_tutorial/" target="_blank">Main page of this tutorial</a>  <br>
      <a href="https://gitlab.com/YingxiaoYan/triplotgui_tutorial" target="_blank">View source of this site on GitLab</a>
      </span>

# execute:
#   freeze: true


format:
  html:
    page-layout: full
    fontsize: 1.1em
    theme:
      - solar
      - styles.scss
    mainfont: Arial
    css: styles.scss
    toc: true
    code-link: true
    anchor-sections: true  ## overing over a section title (e.g. # Heading or ## Subheading) in the rendered HTML will display a clickable anchor link.
    fig-cap-location: margin  ## top bottom margin
    reference-location: margin
    footnotes-hover: true
lightbox: auto   ## zoom in the figure upon clicking

editor: visual  # option in Quarto that enables the Visual Editor mode for editing documents.
