authorname: "TriplotGUI"
draft: false

project:
  type: website
  output-dir: public

  resources:
    - "img/**"
    - "icon/**"
    - "pdf/**"
    - "_extensions/**"
  preview:
    port: 22223
    browser: true
    watch-inputs: true
    navigate: true

title-meta: "TriplotGUI"
description-meta: "Epidemiologist | PhD researcher | Machine learning, computational metabolomics"


name: "TriplotGUI"
website:
  title: "TriplotGUI {{< fa brands gitlab >}}"
  description: "Epidemiologist | PhD researcher | Machine learning, computational metabolomics"
  image: img/TriplotGUI_logo_white.png
  favicon: img/TriplotGUI_logo_white.png
  site-url: "https://yingxiaoyan.gitlab.io/triplotgui_tutorial/"
  repo-url: "https://yingxiaoyan.gitlab.io/triplotgui_tutorial/"
  repo-branch: main

  search:
    location: navbar
    type: textbox

  navbar:
    logo: /img/TriplotGUI_logo_black.png
    pinned: true
    foreground: yellow
    background: black   # It seems title block banner background color change with it
    left:
      - href: introduction.qmd
        text: Introduction
      - href: installation.qmd
        text: Installation
      - href: workflow.qmd
        text: Workflow
      - text: Tutorial(simple)
        menu:
          - href: simple.qmd
            text: User Interface
          - href: simple_code.qmd
            text: Code
      - text: Tutorial(complex)
        menu:
          - href: complex.qmd
            text: User Interface
          - href: complex_code.qmd
            text: Code
      - text: Use Case
        href: use_case.qmd
      - text: Papers
        href: papers.qmd
      - href: about.qmd
        text: About us

    right:
      - icon: folder-symlink
        href: https://yingxiaoyan.gitlab.io/triplotgui_tutorial/
      - icon: "github"
        href: https://gitlab.com/YingxiaoYan/TriplotGUI
      - icon: linkedin
        href: https://www.linkedin.com/in/yingxiao-yan
      - icon: envelope
        aria-label: email
        href: "mailto:yingxiao.yan.007@gmail.com"
  page-footer:
    background: light
    left: |
      <span class="faux-block">&#169; 2024 Yingxiao Yan CC BY-SA 4.0</span>
    center: |
      <span class="faux-block"><a href="https://gitlab.com/YingxiaoYan/TriplotGUI">TriplotGUI gitlab</a></span>
    right: |
      <span class="faux-block cyan"><a href="https://yingxiaoyan.gitlab.io/triplotgui_tutorial/">View source of this site on GitLab</a></span>

execute:
  freeze: true


format:
  html:
    page-layout: full
    fontsize: 1.1em
    theme:
      - solar
      - styles.scss
    mainfont: Nunito
    css: styles.scss
    toc: true
    code-link: true
    anchor-sections: true
    fig-cap-location: margin
    reference-location: margin
    footnotes-hover: true


editor: visual
