---
layout: page
title: Relevant papers
title-block-banner: true
title-block-banner-color: white
excerpt: Relevant papers
comments: false
execute:
  freeze: true  # never re-render during project render
engine: knitr 
paper:
  pdf: "pdf/Triplot_paper.pdf"
---

```{css echo=FALSE}
.embed-container {
    position: relative;
    padding-bottom: 65%;  
    overflow: hidden;
    max-width: 150%;
}
.embed-container iframe,
.embed-container object,
.embed-container embed {
    position: absolute;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
}
```

```{=html}
<p class="text-center">

<a class="btn btn-outline-info btn-lg cv-download" href="`r rmarkdown::metadata$paper$pdf`" target="_blank"> <i class="fa-solid  fa-file-arrow-down"></i>&ensp; Download main paper </a>

</p>
<p class="large-text">

<strong>Main paper</strong>


</p>
```
Schillemans T, Shi L, Liu X, Åkesson A, Landberg R, Brunius C. Visualization and Interpretation of Multivariate Associations with Disease Risk Markers and Disease Risk-The Triplot. Metabolites. 2019 Jul 6;9(7):133. [doi: 10.3390/metabo9070133](https://www.mdpi.com/2218-1989/9/7/133)

::: embed-container
<iframe src="`r rmarkdown::metadata$paper$pdf`" style="border: 5px">

</iframe>
:::

```{=html}
<br>
<p class="large-text">

<strong>Other papers</strong>
</p>
```
Bodén S, Zheng R, Ribbenstedt A, Landberg R, Harlid S, Vidman L, Gunter MJ, Winkvist A, Johansson I, Van Guelpen B, Brunius C. Dietary patterns, untargeted metabolite profiles and their association with colorectal cancer risk. Sci Rep. 2024 Jan 26;14(1):2244. [doi: 10.1038/s41598-023-50567-6](https://www.nature.com/articles/s41598-023-50567-6)

Schillemans T, Yan Y, Ribbenstedt A, Donat-Vargas C, Lindh CH, Kiviranta H, Rantakokko P, Wolk A, Landberg R, Åkesson A, Brunius C. OMICs Signatures Linking Persistent Organic Pollutants to Cardiovascular Disease in the Swedish Mammography Cohort. Environ Sci Technol. 2024 Jan 16;58(2):1036-1047. [doi: 10.1021/acs.est.3c06388](https://pubs.acs.org/doi/full/10.1021/acs.est.3c06388).

Titova OE, Brunius C, Warensjö Lemming E, Stattin K, Baron JA, Byberg L, Michaëlsson K, Larsson SC. Comprehensive analyses of circulating cardiometabolic proteins and objective measures of fat mass. Int J Obes (Lond). 2023 Nov;47(11):1043-1049. [doi: 10.1038/s41366-023-01351-z](https://pubmed.ncbi.nlm.nih.gov/37550405/)
