---
title: "Tutorial(simple) - User Interface"
subtitle: "Simple demo of using user Interface in TriplotGUI"
title-block-banner: true
title-block-banner-color: white
title-block-categories: false

page-layout: full
format:
  html: 
    margin-top: 0em
    margin-bottom: 0em
    padding-top: 0em
    padding-bottom: 0em
    minimal: true
    smooth-scroll: true
    fig-responsive: true
    toc-location: right
    toc-depth: 5
    toc-title: Tutorial
---

```{r, include=FALSE}
##This is a function that combines html and rmarkdown. It aims to generate a button that could hide output or plot (fold.output=T or fold.plot=T).
hooks = knitr::knit_hooks$get()
hook_foldable = function(type) {
  force(type)
  function(x, options) {
    res = hooks[[type]](x, options)
    
    if (!isTRUE(options[[paste0("fold.", type)]])) return(res)
    
    paste0(
      "<details><summary>", type, "</summary>\n\n",
      res,
      "\n\n</details>"
    )
  }
}
knitr::knit_hooks$set(
  output = hook_foldable("output"),
  plot = hook_foldable("plot")
)
```

Before starting, please make sure you have installed the TriplotGUI package following [Setup](installation.qmd){target="_blank"}.


# Data description
Each dataset used in this page of tutorial can be downloaded [here](https://gitlab.com/YingxiaoYan/triplotgui/-/blob/main/Example_data){target="_blank"} as a dataframe in the rds files:

-    Example1_exposure.rds
-    Example1_Omics.rds
-    Example1_outcome.rds
-    Example1_covariate.rds

The Data used for this example originates from ***CAMP_2***, which is a synthetic dataset that was simulated from the authentic data used in a cross-sectional study of carbonhydrate alternatives and metabolic phenotypes in Chinese young adults (Liu et al. 2018). We have selected our exposures, Omics data, outcomes and covariates based on the ***CAMP_2*** data following the code [here](https://gitlab.com/YingxiaoYan/triplotgui/-/blob/main/Tutorial_code/Data_cleaning_CAMP_2.R){target="_blank"}. The brief description of these dataframes is shown as below.

-    Example1_exposure.rds --> exposure1:  11 variables representing the dietary intake as measured by food frequency questionnaires (`"Refined_grains"`, `"Coarse_grains"`, `"Red_meat"`, `"Poutry"`, `"Seafood"`, `"Egg"`, `"Animal_organs"`, `"Vegetables"`, `"Fruits"`, `"Potatos"`, `"Legumes"`.)
-    Example1_Omics.rds -->  Omics1: 20 variables representing plasma metabolites predictive of BMI
-    Example1_outcome.rds --> outcome1: 5 variables representing clinical measurements: `"BMI"`, `"HDL"`(high-density lipoprotein cholesterol), `"LDL"`(low-density lipoprotein cholesterol), `"triglycerides"`, `"total_cholesterol"`.
-    Example1_covariate.rds --> covariate1: 2 variables that can be used as potential confounders: `"AGE"` and `"SEX"`

All dataframes are row-wise matched by observation and consist of 300 synthetic observations.


# Research question
We want to assess the relationship between diet, metabolic profiles and risk factors of metabolic diseases (i.e. BMI, total cholesterol, triglyceride, HDL, LDL).

# The use of interface
Run `TriplotGUI_shiny_tryout` to open your interface. What we will show as an example in the interface here correspond to the [code example steps](https://yingxiaoyan.gitlab.io/triplotgui_tutorial/simple_code.html#step-2){target="_blank"}

## Upload data
First upload 
